name: xor
channels:
  - pytorch
dependencies:
  - jupyter=1.0.0
  - matplotlib=2.1.2
  - numpy=1.14.0
  - python=2.7.14
  - scikit-learn=0.19.1
  - seaborn=0.8.1
  - pytorch=0.3.0
  - torchvision=0.2.0
